# Generated by Django 3.1.5 on 2021-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210318_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categoryy',
        ),
    ]
