# Generated by Django 3.1.5 on 2021-03-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_pic',
        ),
    ]
